config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'

  resources :users
  resources :questions, except: [:show, :new, :index]
  resource :session, only: [:new, :create, :destroy]
  resources :hashtag, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  ITERATIONS = 20_000
  DIGEST = OpenSSL::Digest::SHA256.new
  EMAIL_REGEXP = /[\w.+-]+@[\w.-]+\.[a-zA-Z]{2,4}/
  USERNAME_REGEXP = /\A\w+\z/
  COLOR_REGEXP = /\A\#[\da-fA-Z]{6}\z/
  DEFAULT_COLOR = "#106a65"

  attr_accessor :password

  has_many :questions, dependent: :destroy

  #проверка что email и username не пустые
  validates :email, :username, presence: true
  # проверка формата электронной почты пользователя, уникальный email(без учета регистра)
  validates :email, format: { with: EMAIL_REGEXP }, uniqueness: true

  # проверка формата юзернейма пользователя (только латинские буквы, цифры, и знак _) и на уникальность(без учета регистра)
  # проверка максимальной длины юзернейма пользователя (не больше 40 символов)
  validates :username, format: { with: USERNAME_REGEXP }, uniqueness: true, length: { maximum: 40 }

  # валидация будет проходить только при создании нового юзера
  validates :password, presence: true, on: :create

  # подтверждения пароля
  validates :password, confirmation: true

  validates :background_color, format: { with: COLOR_REGEXP }

  validates :avatar_url, format: { with: URI.regexp }, allow_blank: true

  # перед валидацией переводим username в нижний регистр и т.п.
  before_validation :normalize_user
  # шифрование пароля
  before_save :encrypt_password

  # Основной метод для аутентификации юзера (логина). Проверяет email и пароль,
  # если пользователь с такой комбинацией есть в базе, возвращает этого
  # пользователя. Если нет — возвращает nil.
  def self.authenticate(email, password)
    # Сперва находим кандидата по email
    email&.downcase!
    user = find_by(email: email)

    # Если пользователь не найден, возвращает nil
    return nil unless user.present?

    # Формируем хэш пароля из того, что передали в метод
    hashed_password = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST)
    )

    # Обратите внимание: сравнивается password_hash, а оригинальный пароль так
    # никогда и не сохраняется нигде. Если пароли совпали, возвращаем
    # пользователя.
    return user if user.password_hash == hashed_password

    # Иначе, возвращаем nil
    nil
  end

  # Служебный метод, преобразующий бинарную строку в шестнадцатиричный формат, для удобства хранения.
  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  private

  #в базу username пользователей попадали только в нижнем регистре
  #email в нижнем регистре
  def normalize_user
    username&.downcase!
    email&.downcase!

    # присваиваем цвет по умолчанию, если в поле background_color пусто
    self.background_color = DEFAULT_COLOR if self.background_color.nil?
  end

  def encrypt_password
    if password.present?
      # Создаем т.н. «соль» — случайная строка, усложняющая задачу хакерам по
      # взлому пароля, даже если у них окажется наша БД.
      #У каждого юзера своя «соль», это значит, что если подобрать перебором пароль
      # одного юзера, нельзя разгадать, по какому принципу
      # зашифрованы пароли остальных пользователей
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

      # Создаем хэш пароля — длинная уникальная строка, из которой невозможно
      # восстановить исходный пароль. Однако, если правильный пароль у нас есть,
      # мы легко можем получить такую же строку и сравнить её с той, что в базе.
      self.password_hash = User.hash_to_string(
          OpenSSL::PKCS5.pbkdf2_hmac(password, password_salt, ITERATIONS, DIGEST.length, DIGEST)
      )
      # Оба поля попадут в базу при сохранении (save).
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: [:index, :create, :new]
  # Проверяем, имеет ли юзер доступ к экшену, делаем это для всех действий, кроме
  # :index, :new, :create, :show — к ним есть доступ у всех, даже у анонимных юзеров.
  before_action :authorize_user, except: [:index, :new, :create, :show]

  def index
    @users = User.all
    #теги c вопросами
    @hashtags = Hashtag.left_joins(:hashtags_questions).
      where.not(hashtags_questions: {hashtag_id: nil}).group(:id).order(:text)
    #все теги
    #@hashtags = Hashtag.all.order(:text)
  end

  def new
    # Если юзер залогинен, отправляем его на главную с сообщением
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?

    @user = User.new
  end

  def create
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?

    # создаём нового пользователя с параметрами
    @user = User.new(user_params)

    # Сохраняем
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Вы успешно зарегистрированы!'
    else
      # Если не удалось по какой-то причине сохранить пользователя, то используем метод render (не redirect!),
      # который заново рисует шаблон, и название шаблона
      render 'new'
    end
  end

  def edit
  end

  def update
    # пытаемся обновить юзера
    if @user.update(user_params)
      # Если получилось, отправляем пользователя на его страницу с сообщением
      redirect_to user_path(@user), notice: 'Данные обновлены'
    else
      # Если не получилось, как и в create, рисуем страницу редактирования
      # пользователя со списком ошибок
      render 'edit'
    end
  end

  def show
    @questions = @user.questions.order(created_at: :desc)

    @new_question = @user.questions.build

    #счетчики вопросов, ответов
    @questions_count = @questions.count
    @answers_count = @questions.where.not(answer: nil).count
    @without_answered_count = @questions_count - @answers_count
  end

  def destroy
    #удалим пользователя
    @user.destroy

    flash[:success] = "Пользователь удалён!"
    redirect_to root_path
  end

  private

  def authorize_user
    reject_user unless @user == current_user
  end

  def load_user
    begin
      # защищаем от повторной инициализации с помощью ||=
      @user ||= User.find params[:id]
    rescue ActiveRecord::RecordNotFound => e
      redirect_to root_url, alert: 'Пользователь не найден'
    end
  end

  def user_params
    # берём объект params, потребуем у него иметь ключ
    # :user, у него с помощью метода permit разрешаем
    # набор инпутов. Ничего лишнего, кроме них, в пользователя не попадёт
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :name, :username, :avatar_url, :background_color)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%# Страница редактирования пользователя %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Править профиль</h1>

  <div class="column-1-2">
    <%# С помощью специального хелпера form_for мы делаем тег <form ...> %>
    <%# с нужными аттрибутами, после этого в переменной f будет специальный %>
    <%# объект (form builder object), вызывая методы которого мы можем %>
    <%# создавать теги для нужных нам полей формы. %>
    <%= form_for(@user) do |f| %>
      <%# Вывод ошибок валидации пользователя, если есть. Ошибки содержатся %>
      <%# в поле errors модели (в нашем случае @users). %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%# С помощью методов label и text_field у объекта f мы создаем теги %>
      <%# <label ... > и <input type="text" ... > с нужными атрибуами %>
      <div class="form-field">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <%# Поступаем аналогично для других полей %>
      <div class="form-field">
        <%= f.label 'Ваше имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'URL вашей аватарки', class: 'form-label' %>
        <%= f.text_field :avatar_url, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'Цвет вашей формы', class: 'form-label' %>
        <%= f.color_field :background_color, class: 'form-color-field' %>
      </div>

      <div class="buffer-top-large buffer-bottom">
        Если не хотите менять пароль — оставьте эти поля пустыми!
      </div>

      <div class="form-field">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action buffer-top">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      </div>

      <div class="form-action buffer-top">
        <div class="button button-dark button-small  button-delete">
          <%= link_to 'Удалить профиль', @user, method: :delete,
                      data: { confirm: "Вы уверены?" } %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <% @users.each do |user| %>
    <div class="users-list-item">
      <div class="user-image-div user-image-div-small">
        <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
      </div>
    </div>
  <% end %>

  <%# Этот код выводит все хэштеги, которые есть в базе %>
  <div class="buffer-top">
    <% @hashtags.each do |hashtag| %>
      <div class="question-text text-hashtag">
        <%= link_to hashtag.text, hashtag_url(hashtag.text) %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label :email, 'Логин (email)', class: 'form-label' %>
        <%= f.text_field :email, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :username, 'Никнейм', class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, 'Имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password, 'Пароль', class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action">
        <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-header text-center" style="background-color: <%= @user.background_color %>" >
  <h1 class="title-medium">
    <%# Выводим имя пользователя %>
    <%= @user.name %>
  </h1>

  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user)  if current_user == @user %>
  </div>

  <div class="user-image-div">
    <%# Рисуем аватарку пользователя%>
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">
    <%# Выводим никнейм пользователя с символом «@» перед ним. %>
    @<%= @user.username %>
  </h2>

  <div class="user-ask-button container text-center">
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>
</div>

<div class="user-details">
  <%# Выводим счетчик вопросов, ответов %>
  <div class="user-statistics container text-center">
    <div class="column-1-3">
      <h1 class="title-small"><%= @questions_count %></h1>
      <p><%= inclination(@questions_count, 'вопрос', 'вопроса', 'вопросов') %></p>
    </div>

    <div class="column-1-3">
      <h1 class="title-small"><%= @answers_count %></h1>
      <p><%= inclination(@answers_count, 'ответ', 'ответа', 'ответов') %></p>
    </div>

    <div class="column-1-3">
      <h1 class="title-small"><%= @without_answered_count %></h1>
      <p><%= inclination(@without_answered_count, 'неотвеченный', 'неотвеченных', 'неотвеченных') %></p>
    </div>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <%= form_for @new_question do |f| %>
      <%= f.hidden_field :user_id %>

      <div class="form-field">
        <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
        <%= f.text_area :text, class: 'form-textarea' %>
      </div>

      <%= recaptcha_tags size: 'compact' unless current_user.present? %>

      <div class="form-action">
        <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
      </div>
    <% end %>
  </div>
</div>


<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>