config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'

  resources :users
  resources :questions, except: [:show, :new, :index]
  resource :session, only: [:new, :create, :destroy]
  resources :hashtag, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"/>
    <title>Хорошие вопросы</title>
    <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

  <div class="header">
    <div class="container">
      <div class="header-logo">
        <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
      </div>

      <div class="header-nav">
        <% if current_user %>
          <%= link_to "@#{current_user.username}", user_path(current_user) %> |
          <%= link_to 'Выйти', session_path, data: { method: :delete }  %>
        <% else %>
          <%= link_to 'Зарегистрироваться', new_user_path,
                      class: 'button button-light button-small' %>
          <%= link_to 'Войти', new_session_path,
                      class: 'button button-light button-small' %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="content">
    <% if flash.any? %>
      <div class="content-wrapper buffer-both">
        <% flash.each do |name, message| %>
          <%= content_tag :div, message, class: "flash-#{name}" %>
        <% end %>
      </div>
    <% end %>

    <%# Вместо волшебной конструкции yield рельсы подставят то, что срендерит %>
    <%= yield %>
  </div>

</body>
</html>